version: "3.9"
services:
  nestapp:
    container_name: nextapp
    image: xhepower/nextjs
    volumes:
      - type: bind
        source: .
        target: /app
    build: .
    ports:
      - 3000:3000
